### ISSUE TITLE
Create stub ArtiClient TorProvider implementation

### ISSUE THREAD

**Issue by morganava** [blueprint-freespeech/gosling#91]

**Comment by pospeselr** [comment]
So this is a surprising amount of build work to do properly.

The end result should be cgosling and tor-interface crates which consumers must opt-in to for the various backends. For now we want:
- mock-tor-provider
- legacy-tor-provider
- arti-client-tor-provider

and ultimately adding (names pending):
- arti-daemon-tor-provider
- tor-vpn-tor-provider

So we need to basically enable the relevant modules in tor-interface and the relevant functions in cgosling, as well as our tests. These feature flags therefore need to be enabeld via CMake feature flags (eg ENABLE_MOCK_TOR_PROVIDER=ON) at cconfigure.

We then need to tweak the ENABLE_TEST and ENABLE_ONLINE_TEST to instead use these tor provider flags.

Unfortunately we also will need to tweak our cbindgen -> cgosling.h header pipeline; cbindgen doesn't really handle feature flags in a way that makes sense to me. It still includes functions and stuffs in headers wrapped in preprocessor definitions (if you create the mappings in cargo.toml) in #defines, but doesn't define them anywhere, so it is up to the header consumer to know if the built binary has the relevant feature flag.

My preference is for the generated header to not include the declarations at al so that consumers will get build errors rather than linker errors.

So, the first step is to basically discard the generated cgosling.h header and rebuild it using our existing code generation pipeline used in the bindings projects. Fortunately it is easy enough to discard the parts we don't want when generating  the json intermediate format.

Then we can add the config flags and update our examples and tests.

Finally, we can add additional flags for the arti backend and then we can finally get rolling on actually integrating arti-client.

**Comment by morganava** [comment]
completed in 19befad7311c8e1675d902e75ffea3f94c05fce6
